/**
 * Seed IFCT 2017 Indian food data into Supabase food_items table.
 * Run from repo root:  npx tsx product/scripts/seed-food-items.ts
 *
 * Prerequisites:
 *   1. Run product/supabase/migrations/002_add_food_items.sql in Supabase SQL Editor first.
 *   2. The ifct2017.json file must exist alongside this script (generated by the Python step).
 */

import fs from 'fs'
import path from 'path'
import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in product/.env.local')
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY)

async function main() {
  const jsonPath = path.join(__dirname, 'ifct2017.json')
  const records: Record<string, unknown>[] = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'))
  console.log(`Loaded ${records.length} food items`)

  const BATCH = 50
  let inserted = 0

  for (let i = 0; i < records.length; i += BATCH) {
    const batch = records.slice(i, i + BATCH)
    const { error } = await supabase
      .from('food_items')
      .upsert(batch, { onConflict: 'code' })

    if (error) {
      console.error(`\nBatch ${i}–${i + BATCH} failed:`, error.message)
      process.exit(1)
    }
    inserted += batch.length
    process.stdout.write(`\r${inserted}/${records.length} inserted`)
  }

  console.log(`\nDone — ${inserted} food items seeded into Supabase.`)
}

main().catch(e => { console.error(e); process.exit(1) })
